### ISSUE TITLE
Hot reload babel compile for development 

### ISSUE THREAD

**Issue by noobmaster19** [flexdinesh/npm-module-boilerplate#8]
Hey, love this boilerplate, but one thing issue I'm having is during the development phase.  I'm using `npm link` to make the package available to a testing  react web app, every time I make a small change to the project, I'll need to do a `npm run clean && npm run build` and then do a `npm start` to re run the react app..  I can't use change the entry point of the package.json to read from the src folder because I used arrow functions (which is not compatible, hence the need for babel) . Is there a more efficient way of doing development?

**Comment by neowenshun** [comment]
I was thinking if there's a way to do a hot reload to automatically compile the changes to the lib folder.

**Comment by flexdinesh** [comment]
Mate - this repo is pretty old and I wouldn't recommend using this boilerplate to develop js libs today. [Microbundle](https://github.com/developit/microbundle) is much better and I use it for all my external package development. It has hot-reload, building for different targets and whatnot. Setup is pretty easy too. I highly recommend you use Microbundle instead of this boilerplate. Good luck to you!
